server.port: 8081
server.error.include-message: always

logging:
  level:
    root: INFO

spring:
  application:
    name: Profesores-Application
  data:
    mongodb:
      uri: mongodb+srv://carodriguez19:testingtesting123@cluster0.xpofgue.mongodb.net/
      database: Clientes
      auto-index-creation: true